language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - pip install pep8
install:
  - python setup.py install
script:
  - pep8 configreader.py
  - pylint --rcfile=.pylint.rc configreader.py
  - py.test
